### ISSUE TITLE
Verder automatiseren, interface voor informatie bronnen, samenwerken met 'praktijk' enz

### ISSUE THREAD

**Issue by huib23** [sjerpbouwtsites/faillissementen-scraper#14]
Heel nice Project!!

Lang niet meer met ict van dingtjes beziggehouden maar heb lang na gedacht over  de zoektocht naar leegstand te automatiseren. Nooit na gedacht om faillissementen van het kvk register te gebruiken goed idee!
Wel heb ik nagedacht over andere data om leegstand te vinden te gebruiken namelijk:

  -commissie ruimtelijke kwaliteit Amsterdam: plubliceerd kleine verslagen over vergunning aanvragen van monumentale panden, deze zal uit de html gescrapt kunnen worden. om vervolgens te doorzoeken naar bepaalde termen (denk aan leegstand, weigering, hotel. enz enz .)

  - Omgevings dienst noordzeekanaal gebied, bij hun kun je data opvragen wat betreft bodem vervuiling.

ook heb ik er overgedacht dat het nice zal zijn om een interface hebt waar je alle sites waar vaak iets te vinden is over een pand van zelf doorloopt (ruimtelijkeplannen.nl, bagviewer.nl, Webshop kadaster, oozo.nl, drimble.nl enz..)( en dat je ze miss kan afvinken als het ware zodat je weet dat je niks vergeet)

Het lijkt me nice om miss als je er zin en behoefte om samen te komen met ook de mensen die wat actiever zijn bij 'de praktijk' misschien wil je een keer langs komen bij het kraakspreek uur in oost:

https://radar.squat.net/nl/node/353291

Misschien is het ook een idee om een keer bij de lag af te spreken, misschien ook mogelijk om daar te bespreken of hun server hiervoor gebruikt kan worden en of ze willen helpen met de sercurty (aangezien hacks waar je het over hebt ook):

https://laglab.org/

Voor de rest mja wil je nog wel meegeven dat het misschien iets is om te overwegen is om niet te insinueren dat de data die je aanbiedt bedoelt is om illegale activiteiten uit te voeren dit zal je serieus zwaar in de problemen kunnen brengen. (aanzetten tot en het uitvoeren van misdaad in georginaseerde vorm bv). ook wil ik je meegeven dat krakers niet de enige zijn die zoeken naar leegstand, denk aan criminele, maar ook aan anti kraak bedrijven die actieve marketing methodes hebben.

Supper props nogmaals voor wat je doet!

**Comment by sjerpbouwtsites** [comment]
He @huib23 super bedankt voor je issue en de suggesties!
Ik heb je databron suggesties hierbij gezet: https://github.com/sjerpbouwtsites/faillissementen-scraper/issues/19
Inderdaad belangrijk om bij / met de praktijk bezig te zijn. Hierom organiseerde ik ook een demonstratie in de Bollox vorige maand. Helaas kwam van o.a. Joes niemand opdagen. Dit project heb ik wel bedacht in samenspraak met verschillende (ex-)krakers, maar het kan natuurlijk altijd beter. Beveiliging is inderdaad een kwestie, er valt op dit moment nog niet zoveel te beveiligen, maar dat gaat wel komen. Op de demonstratie kwam wel iemand van het laglab binnenlopen, daar had ik veel aan :) (was jij dat?) En inderdaad dat juridische punt is inderdaad iets om meer over na te denken... ik heb hier al advies over ingewonnen. Eén van de dingen die mij werd gezegd is dat kraakspreekuren ook al sinds jaar en dag in de openheid gebeuren. Maargoed, het spanningsveld herken ik. Dank dat je dat onder de aandacht brengt. Ik roep bewust niet op tot kraken in de app maar toon leegstand. We zullen hier scherp op moeten blijven. 

ik ben de issue lijst aan het opruimen en sluit deze voor nu.
