### ISSUE TITLE
MEETING: kennismaking vrijwilligers, praten over architectuur, stack, ontwerp, skillsets, planning & coordinatie etc.

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/faillissementen-scraper#21]
Jazeker mensen... We moeten om de tafel, al dan niet digitaal. Kan hier even iedereen die geinteresseerd is zich melden?

**Comment by huib23** [comment]
Ik ben geinteresseerd!

**Comment by sjerpbouwtsites** [comment]
> Ik ben geinteresseerd!

top! Kan iedere geinterresseerde zijn email&telefoonnummer sturen naar dev@sjerpbouwtsites.nl. Dat maakt het organiseren een stuk makkelijker.

**Comment by sjerpbouwtsites** [comment]
@huib23 he huib, [neem hier even een kijkje voor schetsen](https://github.com/sjerpbouwtsites/faillissementen-scraper/blob/master/ontwerp-v1/TO.md) van de v1. Als je nog geinteresseerd bent, laat dan even je emailadres achter op dev@sjerpbouwtsites.nl

**Comment by decentral1se** [comment]
o/ hooiiii uit rotterdam! echt leuk wat jullie hier doen. ik heb al de kraakaap met de lokale KSU gedeelt en hoopelijk gaan ze wel goed kijken hoe het werkt! Geen idee hoe ik kan helpen want ik ben niet goed in JS/TS maar als er infrastructuur/hosting/etc. werk nodig is, roep maar :)

**Comment by sjerpbouwtsites** [comment]
Hoi @decentral1se , dank voor het aanbod. Ik ben momenteel volop de nieuwe backend aan het ontwerpen conform het ontwerp. Heb momenteel 4 processen simultaan op verschillende processoren draaien via workers. De hulp die ik nu goed kan gebruiken is juist het zwaardere programmeerwerk. Maar ik zal aan je aanbod denken!

ondertussen sluit ik dit issue. Helaas lijkt het er op dat ik dit project alleen verder afrond, het zij zo, de hulpaanboden an sich waren zeer motiverend.
